[2024-09-07T23:11:30.000+0000] {processor.py:153} INFO - Started process (PID=49681) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:11:30.001+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:11:30.001+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:30.001+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:11:30.977+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:11:31.120+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:31.119+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:ml_pipeline
[2024-09-07T23:11:31.128+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:31.128+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:ml_pipeline
[2024-09-07T23:11:31.136+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:31.136+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:ml_pipeline
[2024-09-07T23:11:31.137+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:31.136+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:11:31.152+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:31.151+0000] {dag.py:2697} INFO - Creating ORM DAG for ml_pipeline
[2024-09-07T23:11:31.170+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:31.170+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2023-01-01T00:00:00+00:00, run_after=2023-01-02T00:00:00+00:00
[2024-09-07T23:11:31.195+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 1.197 seconds
[2024-09-07T23:11:59.659+0000] {processor.py:153} INFO - Started process (PID=49805) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:11:59.670+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:11:59.670+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:59.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:11:59.672+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:11:59.671+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:11:59.672+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:11:59.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.031 seconds
[2024-09-07T23:12:30.207+0000] {processor.py:153} INFO - Started process (PID=49928) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:12:30.208+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:12:30.208+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:12:30.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:12:30.210+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:12:30.209+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:12:30.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:12:30.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.021 seconds
[2024-09-07T23:13:00.718+0000] {processor.py:153} INFO - Started process (PID=50023) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:13:00.721+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:13:00.722+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:13:00.722+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:13:00.731+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:13:00.730+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:13:00.731+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:13:00.756+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.040 seconds
[2024-09-07T23:13:31.200+0000] {processor.py:153} INFO - Started process (PID=50146) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:13:31.202+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:13:31.202+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:13:31.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:13:31.204+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:13:31.203+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:13:31.204+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:13:31.220+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:14:01.941+0000] {processor.py:153} INFO - Started process (PID=50269) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:14:01.943+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:14:01.944+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:14:01.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:14:01.946+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:14:01.945+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:14:01.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:14:01.964+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.029 seconds
[2024-09-07T23:14:32.743+0000] {processor.py:153} INFO - Started process (PID=50362) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:14:32.743+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:14:32.744+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:14:32.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:14:32.745+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:14:32.745+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:14:32.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:14:32.763+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:15:03.059+0000] {processor.py:153} INFO - Started process (PID=50485) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:15:03.060+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:15:03.061+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:15:03.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:15:03.062+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:15:03.061+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:15:03.062+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:15:03.080+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.023 seconds
[2024-09-07T23:15:33.349+0000] {processor.py:153} INFO - Started process (PID=50589) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:15:33.350+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:15:33.351+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:15:33.351+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:15:33.352+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:15:33.352+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:15:33.353+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:15:33.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:16:04.153+0000] {processor.py:153} INFO - Started process (PID=50703) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:16:04.155+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:16:04.156+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:16:04.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:16:04.157+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:16:04.157+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:16:04.158+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:16:04.174+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.023 seconds
[2024-09-07T23:16:34.862+0000] {processor.py:153} INFO - Started process (PID=50827) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:16:34.863+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:16:34.863+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:16:34.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:16:34.864+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:16:34.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:16:34.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:16:34.881+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.021 seconds
[2024-09-07T23:17:05.377+0000] {processor.py:153} INFO - Started process (PID=50929) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:17:05.379+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:17:05.380+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:17:05.380+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:17:05.381+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:17:05.381+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:17:05.381+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:17:05.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:17:36.138+0000] {processor.py:153} INFO - Started process (PID=51045) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:17:36.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:17:36.142+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:17:36.141+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:17:36.143+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:17:36.142+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:17:36.143+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:17:36.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.023 seconds
[2024-09-07T23:18:06.606+0000] {processor.py:153} INFO - Started process (PID=51169) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:18:06.617+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:18:06.617+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:18:06.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:18:06.618+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:18:06.618+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:18:06.619+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:18:06.633+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.030 seconds
[2024-09-07T23:18:37.165+0000] {processor.py:153} INFO - Started process (PID=51264) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:18:37.168+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:18:37.168+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:18:37.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:18:37.169+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:18:37.169+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:18:37.170+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:18:37.186+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.023 seconds
[2024-09-07T23:19:08.030+0000] {processor.py:153} INFO - Started process (PID=51388) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:19:08.032+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:19:08.032+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:19:08.032+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:19:08.034+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:19:08.033+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:19:08.034+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:19:08.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.024 seconds
[2024-09-07T23:19:38.595+0000] {processor.py:153} INFO - Started process (PID=51511) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:19:38.606+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:19:38.606+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:19:38.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:19:38.609+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:19:38.608+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:19:38.609+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:19:38.626+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.035 seconds
[2024-09-07T23:20:09.291+0000] {processor.py:153} INFO - Started process (PID=51606) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:20:09.293+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:20:09.294+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:20:09.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:20:09.295+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:20:09.294+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:20:09.295+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:20:09.312+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.023 seconds
[2024-09-07T23:20:39.799+0000] {processor.py:153} INFO - Started process (PID=51730) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:20:39.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:20:39.811+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:20:39.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:20:39.812+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:20:39.812+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:20:39.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:20:39.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.032 seconds
[2024-09-07T23:21:10.832+0000] {processor.py:153} INFO - Started process (PID=51853) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:21:10.835+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:21:10.835+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:21:10.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:21:10.837+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:21:10.836+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:21:10.837+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:21:10.854+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.025 seconds
[2024-09-07T23:21:41.745+0000] {processor.py:153} INFO - Started process (PID=51948) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:21:41.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:21:41.756+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:21:41.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:21:41.758+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:21:41.757+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:21:41.758+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:21:41.774+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.031 seconds
[2024-09-07T23:22:12.043+0000] {processor.py:153} INFO - Started process (PID=52070) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:22:12.044+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:22:12.044+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:22:12.044+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:22:12.046+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:22:12.045+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:22:12.046+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:22:12.063+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:22:42.519+0000] {processor.py:153} INFO - Started process (PID=52193) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:22:42.531+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:22:42.531+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:22:42.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:22:42.532+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:22:42.532+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:22:42.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:22:42.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.030 seconds
[2024-09-07T23:23:12.924+0000] {processor.py:153} INFO - Started process (PID=52288) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:23:12.935+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:23:12.936+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:23:12.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:23:12.937+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:23:12.937+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:23:12.937+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:23:12.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.032 seconds
[2024-09-07T23:23:43.086+0000] {processor.py:153} INFO - Started process (PID=52411) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:23:43.098+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:23:43.099+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:23:43.099+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:23:43.103+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:23:43.101+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:23:43.103+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:23:43.125+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.044 seconds
[2024-09-07T23:24:13.867+0000] {processor.py:153} INFO - Started process (PID=52534) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:24:13.869+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:24:13.869+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:24:13.869+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:24:13.871+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:24:13.870+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:24:13.871+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:24:13.886+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:24:44.487+0000] {processor.py:153} INFO - Started process (PID=52629) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:24:44.497+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:24:44.498+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:24:44.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:24:44.499+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:24:44.499+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:24:44.499+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:24:44.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.032 seconds
[2024-09-07T23:25:15.125+0000] {processor.py:153} INFO - Started process (PID=52752) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:25:15.137+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:25:15.138+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:25:15.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:25:15.141+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:25:15.140+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:25:15.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:25:15.159+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.038 seconds
[2024-09-07T23:25:45.510+0000] {processor.py:153} INFO - Started process (PID=52856) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:25:45.514+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:25:45.514+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:25:45.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:25:45.516+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:25:45.515+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:25:45.516+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:25:45.530+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:26:16.004+0000] {processor.py:153} INFO - Started process (PID=52970) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:26:16.005+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:26:16.006+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:26:16.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:26:16.007+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:26:16.007+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:26:16.008+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:26:16.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.021 seconds
[2024-09-07T23:26:46.295+0000] {processor.py:153} INFO - Started process (PID=53093) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:26:46.297+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:26:46.297+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:26:46.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:26:46.299+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:26:46.298+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:26:46.299+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:26:46.313+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.020 seconds
[2024-09-07T23:27:16.515+0000] {processor.py:153} INFO - Started process (PID=53188) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:27:16.527+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:27:16.529+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:27:16.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:27:16.532+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:27:16.531+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:27:16.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:27:16.551+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.040 seconds
[2024-09-07T23:27:47.208+0000] {processor.py:153} INFO - Started process (PID=53311) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:27:47.219+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:27:47.220+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:27:47.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:27:47.222+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:27:47.221+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:27:47.223+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:27:47.241+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.035 seconds
[2024-09-07T23:28:17.584+0000] {processor.py:153} INFO - Started process (PID=53435) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:28:17.585+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:28:17.586+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:28:17.586+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:28:17.588+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:28:17.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:28:17.589+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:28:17.611+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.029 seconds
[2024-09-07T23:28:48.007+0000] {processor.py:153} INFO - Started process (PID=53531) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:28:48.017+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:28:48.018+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:28:48.018+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:28:48.019+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:28:48.018+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:28:48.019+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:28:48.033+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.029 seconds
[2024-09-07T23:29:18.486+0000] {processor.py:153} INFO - Started process (PID=53654) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:29:18.499+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:29:18.499+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:29:18.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:29:18.500+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:29:18.500+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:29:18.501+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:29:18.517+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.032 seconds
[2024-09-07T23:29:48.914+0000] {processor.py:153} INFO - Started process (PID=53777) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:29:48.916+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:29:48.917+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:29:48.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:29:48.919+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:29:48.918+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:29:48.920+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:29:48.943+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.033 seconds
[2024-09-07T23:30:19.190+0000] {processor.py:153} INFO - Started process (PID=53872) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:30:19.192+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:30:19.193+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:30:19.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:30:19.194+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:30:19.193+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:30:19.194+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:30:19.210+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:30:49.637+0000] {processor.py:153} INFO - Started process (PID=53994) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:30:49.648+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:30:49.649+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:30:49.649+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:30:49.652+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:30:49.651+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:30:49.653+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:30:49.671+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.036 seconds
[2024-09-07T23:31:20.263+0000] {processor.py:153} INFO - Started process (PID=54089) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:31:20.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:31:20.265+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:31:20.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:31:20.267+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:31:20.266+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:31:20.267+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:31:20.286+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.025 seconds
[2024-09-07T23:31:50.798+0000] {processor.py:153} INFO - Started process (PID=54212) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:31:50.809+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:31:50.810+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:31:50.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:31:50.811+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:31:50.811+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:31:50.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:31:50.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.033 seconds
[2024-09-07T23:32:21.000+0000] {processor.py:153} INFO - Started process (PID=54307) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:32:21.011+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:32:21.012+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:32:21.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:32:21.014+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:32:21.013+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:32:21.014+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:32:21.032+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.034 seconds
[2024-09-07T23:32:51.937+0000] {processor.py:153} INFO - Started process (PID=54431) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:32:51.938+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:32:51.938+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:32:51.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:32:51.940+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:32:51.939+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:32:51.940+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:32:51.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.026 seconds
[2024-09-07T23:33:22.760+0000] {processor.py:153} INFO - Started process (PID=54554) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:33:22.763+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:33:22.763+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:33:22.763+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:33:22.765+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:33:22.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:33:22.765+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:33:22.782+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.026 seconds
[2024-09-07T23:33:53.347+0000] {processor.py:153} INFO - Started process (PID=54649) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:33:53.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:33:53.359+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:33:53.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:33:53.361+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:33:53.360+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:33:53.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:33:53.378+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.034 seconds
[2024-09-07T23:34:23.608+0000] {processor.py:153} INFO - Started process (PID=54772) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:34:23.619+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:34:23.619+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:34:23.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:34:23.621+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:34:23.620+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:34:23.621+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:34:23.636+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.030 seconds
[2024-09-07T23:34:53.858+0000] {processor.py:153} INFO - Started process (PID=54895) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:34:53.870+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:34:53.872+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:34:53.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:34:53.875+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:34:53.874+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:34:53.876+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:34:53.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.045 seconds
[2024-09-07T23:35:24.715+0000] {processor.py:153} INFO - Started process (PID=54990) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:35:24.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:35:24.728+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:35:24.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:35:24.729+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:35:24.729+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:35:24.730+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:35:24.746+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.035 seconds
[2024-09-07T23:35:55.203+0000] {processor.py:153} INFO - Started process (PID=55113) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:35:55.206+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:35:55.206+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:35:55.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:35:55.208+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:35:55.207+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:35:55.208+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:35:55.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.024 seconds
[2024-09-07T23:36:25.663+0000] {processor.py:153} INFO - Started process (PID=55236) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:36:25.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:36:25.666+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:36:25.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:36:25.667+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:36:25.667+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:36:25.668+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:36:25.684+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.023 seconds
[2024-09-07T23:36:56.034+0000] {processor.py:153} INFO - Started process (PID=55331) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:36:56.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:36:56.037+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:36:56.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:36:56.039+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:36:56.038+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:36:56.039+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:36:56.058+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.026 seconds
[2024-09-07T23:37:26.940+0000] {processor.py:153} INFO - Started process (PID=55455) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:37:26.942+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:37:26.943+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:37:26.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:37:26.944+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:37:26.943+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:37:26.944+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:37:26.961+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.024 seconds
[2024-09-07T23:37:57.648+0000] {processor.py:153} INFO - Started process (PID=55559) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:37:57.659+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:37:57.660+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:37:57.660+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:37:57.661+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:37:57.661+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:37:57.661+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:37:57.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.030 seconds
[2024-09-07T23:38:28.037+0000] {processor.py:153} INFO - Started process (PID=55673) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:38:28.040+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:38:28.040+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:38:28.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:38:28.042+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:38:28.041+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:38:28.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:38:28.064+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.034 seconds
[2024-09-07T23:38:58.464+0000] {processor.py:153} INFO - Started process (PID=55796) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:38:58.467+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:38:58.467+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:38:58.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:38:58.469+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:38:58.468+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:38:58.469+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:38:58.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:39:29.114+0000] {processor.py:153} INFO - Started process (PID=55891) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:39:29.115+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:39:29.116+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:39:29.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:39:29.117+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:39:29.117+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:39:29.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:39:29.133+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.021 seconds
[2024-09-07T23:47:28.765+0000] {processor.py:153} INFO - Started process (PID=50) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:47:28.767+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:47:28.768+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:47:28.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:47:28.776+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:47:28.773+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:47:28.777+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:47:28.807+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.048 seconds
[2024-09-07T23:47:59.658+0000] {processor.py:153} INFO - Started process (PID=172) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:47:59.669+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:47:59.669+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:47:59.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:47:59.671+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:47:59.670+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:47:59.671+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:47:59.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.033 seconds
[2024-09-07T23:48:30.493+0000] {processor.py:153} INFO - Started process (PID=275) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:48:30.496+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:48:30.496+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:48:30.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:48:30.499+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:48:30.498+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:48:30.500+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:48:30.519+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.029 seconds
[2024-09-07T23:49:00.751+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:49:00.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:49:00.754+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:49:00.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:49:00.755+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:49:00.755+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:49:00.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:49:00.782+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.036 seconds
[2024-09-07T23:49:31.669+0000] {processor.py:153} INFO - Started process (PID=513) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:49:31.676+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:49:31.676+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:49:31.676+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:49:31.678+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:49:31.677+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:49:31.678+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:49:31.695+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.028 seconds
[2024-09-07T23:50:02.668+0000] {processor.py:153} INFO - Started process (PID=609) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:50:02.671+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:50:02.672+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:50:02.672+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:50:02.673+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:50:02.673+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:50:02.674+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:50:02.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.024 seconds
[2024-09-07T23:50:32.987+0000] {processor.py:153} INFO - Started process (PID=732) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:50:32.997+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:50:32.998+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:50:32.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:50:32.999+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:50:32.999+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:50:32.999+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:50:33.016+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.033 seconds
[2024-09-07T23:51:03.101+0000] {processor.py:153} INFO - Started process (PID=836) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:51:03.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:51:03.102+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:51:03.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:51:03.104+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:51:03.103+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:51:03.104+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:51:03.120+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.022 seconds
[2024-09-07T23:51:33.283+0000] {processor.py:153} INFO - Started process (PID=950) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:51:33.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:51:33.284+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:51:33.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:51:33.285+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:51:33.285+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:51:33.285+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:51:33.303+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.023 seconds
[2024-09-07T23:52:03.351+0000] {processor.py:153} INFO - Started process (PID=1073) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:52:03.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:52:03.362+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:52:03.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:52:03.364+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:52:03.363+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:52:03.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:52:03.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.031 seconds
[2024-09-07T23:52:33.477+0000] {processor.py:153} INFO - Started process (PID=1167) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:52:33.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:52:33.480+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:52:33.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:52:33.481+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:52:33.481+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:52:33.482+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:52:33.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.025 seconds
[2024-09-07T23:53:04.039+0000] {processor.py:153} INFO - Started process (PID=1290) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:04.041+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:53:04.042+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:53:04.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:04.043+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:53:04.042+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 43
    'start_date': datetime(2024, 09, 07),
                                  ^
SyntaxError: invalid token
[2024-09-07T23:53:04.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:04.063+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.026 seconds
[2024-09-07T23:53:08.018+0000] {processor.py:153} INFO - Started process (PID=1329) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:08.018+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:53:08.019+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:53:08.018+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:08.842+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:08.886+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:53:08.885+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:53:08.901+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:53:08.901+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:53:08.920+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.907 seconds
[2024-09-07T23:53:39.284+0000] {processor.py:153} INFO - Started process (PID=1453) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:39.285+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:53:39.286+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:53:39.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:39.599+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:53:39.621+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:53:39.620+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:53:39.637+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:53:39.636+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:53:39.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.374 seconds
[2024-09-07T23:54:10.466+0000] {processor.py:153} INFO - Started process (PID=1558) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:54:10.469+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:54:10.469+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:54:10.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:54:10.925+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:54:10.961+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:54:10.961+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:54:10.983+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:54:10.983+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:54:11.004+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.542 seconds
[2024-09-07T23:54:41.745+0000] {processor.py:153} INFO - Started process (PID=1673) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:54:41.755+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:54:41.756+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:54:41.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:54:42.040+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:54:42.060+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:54:42.060+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:54:42.078+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:54:42.078+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:54:42.099+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.356 seconds
[2024-09-07T23:55:12.987+0000] {processor.py:153} INFO - Started process (PID=1798) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:55:12.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:55:12.990+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:55:12.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:55:13.296+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:55:13.316+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:55:13.316+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:55:13.331+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:55:13.331+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:55:13.356+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.371 seconds
[2024-09-07T23:55:44.029+0000] {processor.py:153} INFO - Started process (PID=1901) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:55:44.031+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:55:44.031+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:55:44.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:55:44.372+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:55:44.402+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:55:44.402+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:55:44.421+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:55:44.421+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:55:44.436+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.410 seconds
[2024-09-07T23:56:14.865+0000] {processor.py:153} INFO - Started process (PID=2018) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:56:14.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:56:14.867+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:56:14.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:56:15.172+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:56:15.195+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:56:15.195+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:56:15.211+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:56:15.211+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:56:15.226+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.364 seconds
[2024-09-07T23:56:45.765+0000] {processor.py:153} INFO - Started process (PID=2142) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:56:45.767+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:56:45.768+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:56:45.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:56:46.063+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:56:46.085+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:56:46.085+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:56:46.101+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:56:46.101+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:56:46.126+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.364 seconds
[2024-09-07T23:57:16.410+0000] {processor.py:153} INFO - Started process (PID=2238) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:57:16.411+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:57:16.412+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:57:16.411+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:57:16.710+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:57:16.731+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:57:16.731+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:57:16.748+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:57:16.748+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:57:16.764+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.357 seconds
[2024-09-07T23:57:39.671+0000] {processor.py:153} INFO - Started process (PID=2316) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:57:39.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:57:39.683+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:57:39.683+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:57:40.002+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:57:40.056+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:57:40.056+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:57:40.065+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:57:40.065+0000] {dag.py:2697} INFO - Creating ORM DAG for ml_pipeline
[2024-09-07T23:57:40.074+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:57:40.074+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:57:40.089+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.421 seconds
[2024-09-07T23:58:10.150+0000] {processor.py:153} INFO - Started process (PID=2443) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:58:10.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:58:10.151+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:58:10.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:58:10.448+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:58:10.471+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:58:10.470+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:58:10.486+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:58:10.486+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:58:10.499+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.352 seconds
[2024-09-07T23:58:40.521+0000] {processor.py:153} INFO - Started process (PID=2548) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:58:40.522+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:58:40.522+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:58:40.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:58:40.852+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:58:40.878+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:58:40.878+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:58:40.895+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:58:40.895+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:58:40.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.390 seconds
[2024-09-07T23:59:10.967+0000] {processor.py:153} INFO - Started process (PID=2667) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:59:10.968+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:59:10.969+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:59:10.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:59:11.280+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:59:11.304+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:59:11.304+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:59:11.322+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:59:11.322+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:59:11.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.373 seconds
[2024-09-07T23:59:42.242+0000] {processor.py:153} INFO - Started process (PID=2791) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:59:42.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2024-09-07T23:59:42.245+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:59:42.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:59:42.537+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2024-09-07T23:59:42.559+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:59:42.558+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2024-09-07T23:59:42.575+0000] {logging_mixin.py:137} INFO - [2024-09-07T23:59:42.575+0000] {dag.py:3427} INFO - Setting next_dagrun for ml_pipeline to 2024-09-07T00:00:00+00:00, run_after=2024-09-08T00:00:00+00:00
[2024-09-07T23:59:42.588+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.349 seconds
